### ISSUE TITLE
set default monit['config']['listen'] to node['ipaddress']?

### ISSUE THREAD

**Issue by vkhatri** [bbg-cookbooks/monit-ng#13]
hello! how do you think about setting monit['config']['listen'] to node['ipaddress']?

afaik, it can be set to '127.0.0.1', but can not be set to node['ipaddress'] using a chef role.

i will submit a PR if it sound good.

**Comment by nathwill** [comment]
i think defaulting to only listening locally is preferable. exposing a service on the public interface should be a conscious decision.

**Comment by vkhatri** [comment]
@nathwill thanks!
