### ISSUE TITLE
generate a separate 'set mailserver' config option for each mail servers

### ISSUE THREAD

**Issue by vkhatri** [bbg-cookbooks/monit-ng#18]
per documentation, multiple email servers must be `,` separated. But, it throws syntax error.

While configuring separate `set mailserver` for each email server, it works without any error.

template needs to be modified to generate `set mailserver` config for each mail server.

**Comment by nathwill** [comment]
so, [docs](http://mmonit.com/monit/documentation/monit.html#Setting-a-mail-server-for-alert-delivery) describe this being handled with a comma-separated list of servers; i think reissuing the `set mailserver` directive repeatedly would just cause the last-issued to apply, rather than providing a fallback server as intended.

**Comment by vkhatri** [comment]
i remember I tested it and it works as fallback looking at the log file. I
will do the testing once more. comma separated email server config throws
syntax error for me, I think Amazon Linux is setting version 5.4.1.

**Comment by vkhatri** [comment]
@nathwill with multiple / separate `set mailserver` config statements, if first server is unreachable monit tries the next available server.

although, `,` separated multiple mail server config is not accepted by monit, throws syntax error. version - `monit-5.2.5-3.11.amzn1.x86_64`, sorry its not 5.4.1 - may be its new syntax.

config:
```ruby
set mailserver mailserver1
set mailserver localhost
```

logs:
```shell
[UTC Mar  2 08:16:30] info     : 'system_host' Monit started
[UTC Mar  2 08:16:36] error    : Cannot open a connection to the mailserver 'mailserver1:25' -- Connection timed out
[UTC Mar  2 08:16:36] info     : Trying the next mail server 'localhost:25'
```

**Comment by nathwill** [comment]
weird that observed behavior is different from documented, but that at least makes the templating easier :)

**Comment by vkhatri** [comment]
:+1:
