### ISSUE TITLE
stop_as support?

### ISSUE THREAD

**Issue by mattadair** [bbg-cookbooks/monit-ng#19]
Would you mind adding stop_as support?  We're using monit to control applications that require a specific uid for both start AND stop.

**Comment by nathwill** [comment]
yeah, seems like a good addition. i'll see if i can find some time this week. if you need it sooner, PRs welcome :)

**Comment by nathwill** [comment]
this shipped in 1.5.2, please feel free to file an issue if you run into any trouble with the new attribute.
