### ISSUE TITLE
check_id is only used when check_type is set, but is required

### ISSUE THREAD

**Issue by jorhett** [bbg-cookbooks/monit-ng#35]
I'm trying to mask monit instance restarts (because you restart it every Chef run) but this doesn't work:

```
monit_check 'localhost' do
  check_type   'system'
  alert        'jo@chegg.com'
  but_not_on   true
  alert_events ['instance']
end
```

because

```
================================================================================
    Error executing action `create` on resource 'monit_check[localhost]'
    ================================================================================

    Chef::Exceptions::ValidationFailed
    ----------------------------------
    Required argument check_id is missing!
```

check_id is only used by the template when id_type is set... which isn't true in this situation. From your own resource:

```
def check_pairs
        {
          'process' => %w( pidfile matching ), 'procmatch' => %w( matching ),
          'file' => %w( path ), 'fifo' => %w( path ),
          'filesystem' => %w( path ), 'directory' => %w( path ),
          'host' => %w( address ), 'system' => %w(),
          'program' => %w( path )
        }
      end
```

**Comment by nathwill** [comment]
nice catch! thanks for the report :)

**Comment by jorhett** [comment]
Note FYI that because system is really the only thing that doesn't require it, I would totally accept a documentation fix that says "hey you need a fake value for this". I opened the issue since I had to spend some time reading the code to figure out wtf ;-)

I think that in general the LWRP needs better docs. And yeah I know "pull requests accepted" ;)

...Or a fix that sets a fake value if check_type is system.

**Comment by nathwill** [comment]
yeah, fixing the docs on this cookbook has been a TODO item for quite a while; especially with all the new resource attributes getting added lately, the useage examples are increasingly worthless. one of these days Real Soon Now (TM)...

as for a fix for this issue, i'd definitely want to fix it so it actually works :smile:. i don't think that should be too hard, so probably not worth band-aiding with a doc update about faking it.
