### ISSUE TITLE
Kill switch capability on service start/restart?

### ISSUE THREAD

**Issue by mattadair** [bbg-cookbooks/monit-ng#38]
It's a bit of an odd situation, but we have situations where monit is already installed and switched off while we're doing work on either the OS, Java applications, or the databases the Java applications use.  In some cases we need a Chef run before we're actually done with the work, and in every case monit-ng sees the installed monit service not running and immediately enables and restarts it.  This immediately brings up our apps before we're ready, causing a bit of havoc.  We're currently working around it by unmonitoring everything before maintenance, but that has caused a couple of issues as you can imagine.

Would it be strange to have a default attribute that could be overridden so that the monit-ng cookbook won't touch the service for a start or restart?

Thanks!
-Matt

**Comment by nathwill** [comment]
Hey Matt,

We're doing the same thing with the unmonitoring for maintenance, mostly casualty free (though not perfectly :hankey:). I'm definitely open to the idea. Do you want to send over a PR?

Cheers,

Nathan

**Comment by nathwill** [comment]
out in 2.0.2
