### ISSUE TITLE
error    : Status not available -- the monit daemon is not running

### ISSUE THREAD

**Issue by yazgoo** [bbg-cookbooks/monit-ng#49]
Hi,

I'm running monit-ng in chef-provisioning on Ubuntu 15.04, via:

````ruby
    recipe "monit-ng"
````

I'm getting:

    error    : Status not available -- the monit daemon is not running

This seems fixed when I do a

    $ sudo monit

So I've added

````ruby
execute "sudo monit"
````

to service.rb.

Do you have any suggestion on the matter ?
Thanks

**Comment by tarcinil** [comment]
I am running into this issue as well, but I was able to resolve it through the actual configuration.

```
$ monit summary
Status not available -- the monit daemon is not running
```

```
$ cat /etc/redhat-release 
CentOS release 6.7 (Final)
```

```
$ which monit
/usr/local/bin/monit
```

I added `set pidfile /var/run/monit.pid` to the `/etc/monitrc`

```
$ monit summary
The Monit daemon 5.14 uptime: 4m 

Process 'REDACTED'            Running
System 'REDACTED'                     Running
```

PR to follow-up
