### ISSUE TITLE
Why is there a max arg limit for start and stop values?

### ISSUE THREAD

**Issue by thenovices** [bbg-cookbooks/monit-ng#55]
See: https://github.com/bbg-cookbooks/monit-ng/blob/master/libraries/monit_check.rb#L23

Why is this max arg limit necessary?

**Comment by nathwill** [comment]
https://github.com/bbg-cookbooks/monit-ng/issues/43

**Comment by thenovices** [comment]
Thanks! And presumably the latest versions of monit aren't affected by this right?

**Comment by nathwill** [comment]
I honestly don't know, but tend to think super-long args are to be discouraged regardless. at that point I'd rather have a helpfully named script or write a proper service definition and then give monit the service management cmds.
