### ISSUE TITLE
Provide more than one group for `monit_check`

### ISSUE THREAD

**Issue by smt116** [bbg-cookbooks/monit-ng#60]
Hi there,

It is possible to [define more than one service's group](https://mmonit.com/monit/documentation/monit.html#SERVICE-GROUPS) in monit check configuration. However `group` attribute [is defined as a `String`](https://github.com/bbg-cookbooks/monit-ng/blob/32d5a34878d064541c4f395a336200a6d1465e58/libraries/monit_check.rb#L32) in monit-ng. What do you think about adding a support for multiple groups here?

It can be achieved in three ways:

1. Change `group` to accept both, string and array types and recognize it in template.
2. Rename `group` into `groups` and force everybody to use an array type even for a single item.
3. Allow to use both, `group` and `groups` and add them in template.

Personally i would go with the first one as it seems to be the most "user friendly". What do you think? I can prepare a pull request if you agree on this.

**Comment by nathwill** [comment]
@smt116 i agree, option 1 is the most user-friendly and backwards-compatible solution. thanks for the report, i look forward to the PR!
