### ISSUE TITLE
Support status on service resource

### ISSUE THREAD

**Issue by webframp** [bbg-cookbooks/monit-ng#64]
https://github.com/bbg-cookbooks/monit-ng/blob/master/recipes/service.rb#L26 

doesn't declare that it supports the `status` command, it should have the `status` set to `true` for the `supports` property

**Comment by nathwill** [comment]
cool, thanks @webframp

**Comment by nathwill** [comment]
just shipped in 2.3.1, which is now up on supermarket. thanks again!
