### ISSUE TITLE
Add template variable for monit check

### ISSUE THREAD

**Issue by maxnasonov** [bbg-cookbooks/monit-ng#69]
There should be a way to override template name. Currently it is a hardcoded "monit.check.erb" value. I've added a request https://github.com/bbg-cookbooks/monit-ng/pull/68 but for some reason it is failing.

**Comment by nathwill** [comment]
ok, got the CI system all fixed up, and got your commit merged, it's up on supermarket in 2.3.3. thanks for the PR and your patience while i got that sorted out!
