### ISSUE TITLE
chef 13 compatibility in monit.conf.erb (was Clarify configuration)

### ISSUE THREAD

**Issue by StuporHero** [bbg-cookbooks/monit-ng#71]
Can you provide examples of how to set the configuration in attribute files? It appears that they should be assigned arrays of hashes with the appropriate data elements, but this does not jive with the default template which apparently uses dot notation to try to access the data. Either the template should use the proper hash key syntax (for example `mailserver['hostname']` instead of `mailserver.hostname`), or an example should be given demonstrating how this is supposed to be used so future users don't have to chase their tails for days trying to figure out what's wrong with their config.

**Comment by nathwill** [comment]
hey @StuporHero.

first off: easy on the passive-aggressiveness, nobody working on this cookbook owes you a thing; if you don't like the cookbook, there's other options.

second: this looks to have recently changed with the release of chef 13; in my testing, it didn't matter whether you used string or symbols for the hash keys in chef 12, it would work the same, whereas in chef 13, the dot-notation fails no matter how you format the attributes.

this is obviously something that will need to be fixed for this cookbook to work with chef 13, so i'm updating the title for your issue and will work on this as a chef-13 compat fix.

**Comment by StuporHero** [comment]
I'd prefer that you stick to talking about the software. My pull request should solve this bug.

**Comment by nathwill** [comment]
samesies ;). PR merged, thanks!

**Comment by nathwill** [comment]
pushed to supermarket as 2.4.0.

**Comment by StuporHero** [comment]
Thanks for the quick turnaround.
